name: Build

on: push

jobs:
  release:
    timeout-minutes: 15
    continue-on-error: true
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
          - uses: actions/checkout@v3
          - name: Use Node.js
            uses: actions/setup-node@v3
            with:
              node-version: 10
          - run: npm install
          - run: electron-forge make
