name: Electron Forge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 15
    continue-on-error: true
    runs-on: ${{ matrix.os-version }}

    strategy:
      matrix:
        os-version: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: "lts"
      - run: npm install
      - run: electron-forge make
